{% set name = "simmer" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54e0cc2c0baa63ce43bceb50e51ed954287dd760463c52cd2a70a3b2dac4c56b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - astropy >=5.1
    - cerberus >=1.3
    - matplotlib-base
    - numpy >=1.19.1
    - openpyxl =3.0.7
    - pandas >=1.2.3
    - pillow =8.2.0
    - pip
    - python >=3.8
    - pyyaml >=5.3
    - scikit-image =0.18.1
    - scipy >=1.6.0
    - tqdm
    - photutils >=1.5.0
    - numba
    - emcee

test:
  imports:
    - simmer
    - simmer.Examples
    - simmer.Examples.PHARO
    - simmer.Examples.Shane
    - simmer.schemas
    - simmer.tests


about:
  home: https://github.com/arjunsavel/SImMER
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source astronomical image reduction pipeline.
  doc_url: https://simmer.readthedocs.io
  dev_url: https://github.com/arjunsavel/SImMER

extra:
  recipe-maintainers:
    - arjunsavel
