{% set name = "simmer" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 79ad18f367304ef0982457822d641f18b92ae41cb83540aee02724d2957b403d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >3.6
  run:
    - astropy =4.0
    - cerberus =1.3
    - matplotlib-base <3.1.1,>=3.0.1
    - nbconvert =5.6.1
    - nbsphinx =0.5.1
    - numpy =1.19.1
    - openpyxl =3.0.4
    - pandas <=1.0
    - pillow =7.2.0
    - pip
    - pygments =2.6.1
    - python >3.6
    - pyyaml =5.3
    - scikit-image =0.17.2
    - scipy =1.5
    - tqdm
    - photutils >=0.7.2

test:
  imports:
    - simmer
    - simmer.Examples
    - simmer.Examples.PHARO
    - simmer.Examples.Shane
    - simmer.schemas
    - simmer.tests
  commands:
    - cd $PREFIX/lib/python3.7/site-packages/
    - mkdir src
    - mv simmer src/simmer
    - python3 -m unittest discover src

about:
  home: https://github.com/arjunsavel/SImMER
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source astronomical image reduction pipeline.
  doc_url: https://simmer.readthedocs.io
  dev_url: https://github.com/arjunsavel/SImMER

extra:
  recipe-maintainers:
    - arjunsavel
