{% set name = "simmer" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0780ff433ff0b42fdcaef1aca174d1c56f3bd7559db57b721e29fb3eebd912c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >3.6
  run:
    - astropy =4.0
    - cerberus =1.3
    - matplotlib-base <3.1.1,>=3.0.1
    - nbconvert =5.6.1
    - nbsphinx =0.8.6
    - numpy >=1.19.1
    - openpyxl =3.0.7
    - pandas =1.2.3
    - pillow =8.2.0
    - pip
    - pygments =2.6.1
    - python >3.6
    - pyyaml =5.3
    - scikit-image =0.18.1
    - scipy <1.5.3, >=1.1.0
    - tqdm
    - photutils >=0.7.2

test:
  imports:
    - simmer
    - simmer.Examples
    - simmer.Examples.PHARO
    - simmer.Examples.Shane
    - simmer.schemas
    - simmer.tests
  commands:
    - cd $PREFIX/lib/python3.7/site-packages/
    - mkdir src
    - mv simmer src/simmer
    - python3 -m unittest discover src

about:
  home: https://github.com/arjunsavel/SImMER
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source astronomical image reduction pipeline.
  doc_url: https://simmer.readthedocs.io
  dev_url: https://github.com/arjunsavel/SImMER

extra:
  recipe-maintainers:
    - arjunsavel
